# Generated by Django 2.2.11 on 2020-03-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_up', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
    ]
