# Generated by Django 2.2.11 on 2020-03-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_up', '0002_customer_no_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
