version: '3'

services:
  db:
    image: postgres:11
  web:
    build: .
    image: take-a-number_customer:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/customer_app
    ports:
      - "8000:8000"
    depends_on:
      - db
  tailwind:
    image: take-a-number_customer:latest
    command: npx tailwindcss build styles.css -o static/output.css
    volumes:
      - .:/customer_app
